spring.application.name=user-stories-prod
spring.datasource.url=jdbc:postgresql://localhost:5432/user-stories-prod
spring.datasource.username=postgres
spring.datasource.password=Wzv-05-zv
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=false
server.port=8080